### ISSUE TITLE
Add Initial Content

### ISSUE THREAD

**Issue by kennethavendano** [csctd/profile-website-kennethavendano#3]
- [ ] Add projects
- [ ] Add resume
- [ ] Add headshots

**Comment by kennethavendano** [comment]
![IMG_2572](https://github.com/csctd/profile-website-kennethavendano/assets/141265820/15bb8c90-71be-4015-9e4b-31e2575f72c8)

**Comment by sarmenti7** [comment]
Nice work! Can you combine some of these pages together to simplify your navigation menu?
